### PR TITLE
Add finding category to sr content

### PR DESCRIPTION
**Pull request by hackermd**
This PR adds the Finding Category concept, which will be included into the standard via CP 2176.

### CODE REVIEW

**Comment by CPBridge** [comment]
Can't fault the implementation, but why is this only in TID1501 and not TID1410 and TID1411 (Planar/Volumetric ROI Measurements and Qualitative Evaluations)?

**Comment by hackermd** [comment]
> Can't fault the implementation, but why is this only in TID1501 and not TID1410 and TID1411 (Planar/Volumetric ROI Measurements and Qualitative Evaluations)?

You are referring to the CP? Good point! I agree, it should be included in all three of them. @dclunie could you kindly update the CP accordingly?

**Comment by hackermd** [comment]
@CPBridge just to confirm we are on the same page. In the implementation, the property is only implemented on `MeasurementsAndQualitativeEvaluations` (corresponding to TID1501), but the other templates inherit from that class.

**Comment by hackermd** [comment]
@dclunie I just double-checked the CP and it's included in all three templates. Sorry for the confusion.

**Comment by CPBridge** [comment]
Ah ok, sorry. I was getting confused about the inheritance hierarchy. Makes sense

**Review by CPBridge — APPROVED** [review]

**Pull request merged**
